red_color:
  name: red
  presentation: Red
  position: 1
  option_type: color
green_color:
  name: green
  presentation: Green
  position: 1
  option_type: color
black_color:
  name: black
  presentation: Black
  position: 1
  option_type: color

