breakfast_tiffany:
  name: "Breakfast At Tiffany's - Paramount Centennial Collection (Mastered in High Definition) (1961)"
  description: "No film better utilizes Audrey Hepburn's flighty charm and svelte beautythan this romantic adaptation of Truman Capote's novella. Hepburn's urban sophisticate Holly Golightly, an enchanting neurotic living off the gifts of gentlemen, is a bewitching figure in designer dresses and costume jewelry. George Peppard is her upstairs neighbor, a struggling writer and \"kept\" man financed by a steely older woman (Patricia Neal). His growing friendship with the lonely Holly soon turns to love and threatens the delicate balance of both of their compromised lives. Taking liberties with Capote's bittersweet story, director Blake Edwards and screenwriter George Axelrod turn New York into a city of lovers and create a poignant portrait of Holly, a frustrated romantic with a secret past and a hidden vulnerability. Composer Henry Mancini earned Oscars for the hit song \"Moon River\" and his tastefully romantic score. The only sour note in the whole film is Mickey Rooney's demeaning performance as the apartment's Japanese manager, an offensively overdone stereotype even in 1961. The rest of the film has weathered the decades well. Edwards's elegant yet light touch, Axelrod's generous screenplay, and Hepburn's mix of knowing experience and naiveté combine to create one of the great screen romances and a refined slice of high society bohemian chic. --Sean Axmaker"
  available_on: <%= Time.zone.now.to_s(:db) %>
  permalink: breakfast-tiffany
  count_on_hand: 0
  ean: 5055055903603

godfather:
  name: "The Godfather - The Coppola Restoration (1972)"
  description: "Francis Ford Coppola's epic masterpiece features Marlon Brando in his Oscar©-winning role as the patriarch of the Corleone family. Director Coppola paints a chilling portrait of the Sicilian clan's rise and near fall from power in America, masterfully balancing the story between the Corleone's family life and the ugly crime business in which they are engaged. Based on Mario Puxo's best-selling novel and featuring career-making performances by Al Pacino, James Cann and Robert Duvall, this searing and brilliant film garnered ten Academy Award® nominations, and won three including Best Picture of 1972."
  available_on: <%= Time.zone.now.to_s(:db) %>
  permalink: godfather
  count_on_hand: 0
  ean: 9780099528128

death_of_a_hero:
  name: "Death of a Hero [Paperback]"
  description: "\"Death of a Hero\", published in 1929 was the author\'s literary response to the war. He went on to publish several works of fiction. In 1942, having moved to the United States, he began to write biographies. This last work was very controversial, as it was highly critical of the man still regarded as a war hero."
  available_on: <%= Time.zone.now.to_s(:db) %>
  permalink: death-of-a-hero
  count_on_hand: 0
  ean: 978-0919614789

lenovo_thinkpad_t410s:
  name: Lenovo Thinkpad T410s mit Intel Core i5 560M 2.66GHz (Win 7/UMTS) - Notebook/Laptop
  description:  "Beschreibung 1\n 38,5cm (14.1\") WXGA+ | 4096 MB DDR3-RAM | 160 GB SSD | Intel HD Graphics | DVD DL Multi Writer | Windows 7 Professional 64\nBeschreibung 2 ThinkPad Notebooks der T Serie kombinieren modernste Technik mit dem legendären ThinkPad Design. Was immer Sie wollen, die T Serie bietet es Überlegene Leistung, handliches Format, maximale Mobilität, lange Akkulaufzeit und hohe Energieeffizienz."
  available_on: <%= Time.zone.now.to_s(:db) %>
  permalink: lenovo-thinkpad-t410s
  count_on_hand: 0
  ean: 0885976811962

compaq_nc6000:
  name: compaq nc6000 P-M 1.6 GHz 512M/40G 14.1
  description: Stylishly designed for the mobile professional, this notebook combines performance and mobility. Features include a bright 14-inch display, versatile MultiBay, and up to 5 hours of battery life with the standard 6-cell battery.
  available_on: <%= Time.zone.now.to_s(:db) %>
  permalink: compaq-nc6000
  count_on_hand: 0
  ean: 000B0001YXWK0

sony_vgn_cs21s_t:
  name: VGN-CS21S/T - Notebook/Laptop
  description: "A design that in a choice of five attractive and vibrant colors with a piano lacquer-like surface attracts everyone's attention. The choices are \"Cotton White\", \"coral pink\", \"Liquorice Black,\" \"Blazing Red\" and \"Caramel Cream.\""
  available_on: <%= Time.zone.now.to_s(:db) %>
  permalink: sony-vgn-cs21s-t
  count_on_hand: 0
  ean: 000B0054QJ2BS
